name: spin_wheel
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_fortune_wheel: ^1.3.2
  cloud_firestore: ^5.6.1
  firebase_auth: ^5.4.0
  firebase_core: ^3.10.0
  get: 
  google_fonts: ^4.0.3
  lottie: ^3.3.1
  shared_preferences: ^2.3.5
  confetti: ^0.8.0
  firebase_messaging: ^15.2.0
  flutter_local_notifications: ^18.0.1
  permission_handler:
  flutter_launcher_icons:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animation/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.jpg" # Make sure this path is correct
